monitor_index: 1
control_monitor_index: 0
rotate_deg: 0
ui_rotate_deg: 0
ui_offsets:
  prompt:
    x: 0
    y: 0
  result:
    x: 0
    y: 0
mirror: true
camera:
  tracking_index: 0
  display_index: 1
target_fps: 60
dry_run: false
timers:
  rolling: 1.5
  result: 2.0
  cooldown: 2.0
detection:
  hsv_min:
  - 0
  - 0
  - 255
  hsv_max:
  - 0
  - 255
  - 255
  blur_kernel: 11
  morph_kernel: 1
  morph_iterations: 1
  min_contour_area: 1.0
  min_circularity: 0.08999999999999975
  processing_interval: 0.04
  buffer_duration: 0.6
  min_wave_span: 0.05
  min_wave_velocity: 0.05
  cooldown: 1.5
  ir_enabled: true
  ir_buffer_duration: 0.35
  ir_score_threshold: 0.12999999999999975
  ir_release_threshold: 0.05999999999999983
  ir_debounce: 0.8
  roi:
    x: 0.0
    y: 0.0
    width: 0.8800000000000001
    height: 1.0
calibration:
  enabled: false
  file: /Users/samste/Desktop/terp-mirror/calibration.yaml
  apply_prompt: true
  apply_spinner: true
  apply_result: true
prizes:
  track_stock: true
  stock:
    Candy + Stickers: 20
    OG Terpscoop: 10
    Lighter Case: 0
    XL Terpscoop: 1
    Terpz T-Shirt: 5
  grand_prize: 1
