monitor_index: 0
rotate_deg: 90
mirror: true
camera:
  index: 0
target_fps: 60
dry_run: false
timers:
  rolling: 3.0
  result: 3.0
  cooldown: 2.5
detection:
  hsv_min: [0, 120, 120]
  hsv_max: [40, 255, 255]
  blur_kernel: 11
  morph_kernel: 5
  morph_iterations: 1
  min_contour_area: 1500
  buffer_duration: 0.6
  min_wave_span: 0.2
  min_wave_velocity: 0.4
  cooldown: 1.5
  ir_enabled: true
  ir_buffer_duration: 0.35
  ir_score_threshold: 0.6
  ir_release_threshold: 0.4
  ir_debounce: 1.0
  roi:
    x: 0.2
    y: 0.1
    width: 0.6
    height: 0.8
prizes:
  track_stock: true
  stock:
    Candy + Stickers: 50
    OG Terpscoop: 40
    Lighter Case: 20
    XL Terpscoop: 10
    Terpz T-Shirt: 5
  grand_prize: 2
calibration:
  enabled: false
  file: calibration.yaml
  apply_prompt: true
  apply_spinner: true
  apply_result: true
