monitor_index: 1
rotate_deg: 0
mirror: true
camera:
  index: 1
target_fps: 60
dry_run: false
timers:
  rolling: 1.5
  result: 2
  cooldown: 2
detection:
  hsv_min: [0, 0, 255]
  hsv_max: [0, 255, 255]
  blur_kernel: 11
  morph_kernel: 5
  morph_iterations: 1
  min_contour_area: 300
  min_circularity: 0.65
  processing_interval: 0.04
  buffer_duration: 0.6
  min_wave_span: 0.2
  min_wave_velocity: 0.4
  cooldown: 1.5
  ir_enabled: true
  ir_buffer_duration: 0.35
  ir_score_threshold: 0.65
  ir_release_threshold: 0.55
  ir_debounce: 0.8
  roi:
    x: 0.1
    y: 0.1
    width: 0.8
    height: 0.8
prizes:
  track_stock: true
  stock:
    Candy + Stickers: 50
    OG Terpscoop: 40
    Lighter Case: 20
    XL Terpscoop: 10
    Terpz T-Shirt: 5
  grand_prize: 2
calibration:
  enabled: false
  file: calibration.yaml
  apply_prompt: true
  apply_spinner: true
  apply_result: true
