monitor_index: 1
control_monitor_index: 0
rotate_deg: 0
ui_rotate_deg: 90
ui_offsets:
  prompt:
    x: -30
    y: -355
  result:
    x: 0
    y: 0
mirror: true
camera:
  tracking_index: 0
  display_index: 1
target_fps: 60
dry_run: false
timers:
  rolling: 1.5
  result: 3.0
  cooldown: 0.5
detection:
  hsv_min:
  - 0
  - 0
  - 230
  hsv_max:
  - 0
  - 255
  - 255
  blur_kernel: 3
  morph_kernel: 1
  morph_iterations: 1
  min_contour_area: 1.0
  min_circularity: 0.08999999999999975
  processing_interval: 0.01
  buffer_duration: 0.8000000000000002
  min_wave_span: 0.05
  min_wave_velocity: 0.05
  cooldown: 1.5
  ir_enabled: true
  ir_buffer_duration: 0.10000000000000002
  ir_score_threshold: 0.3899999999999998
  ir_release_threshold: 0.6200000000000001
  ir_debounce: 0.2
  roi:
    x: 0.0
    y: 0.0
    width: 0.74
    height: 1.0
calibration:
  enabled: false
  file: /Users/samste/Desktop/terp-mirror/calibration.yaml
  apply_prompt: true
  apply_spinner: true
  apply_result: true
prizes:
  track_stock: true
  stock:
    Terp Scoop: 70
    Candy + Sticker: 70
    Coupon: 42
    Lighter Case: 25
    T-Shirt: 6
  grand_prize: 0
