monitor_index: 0
rotate_deg: 90
mirror: true
camera:
  index: 0
target_fps: 60
dry_run: false
timers:
  rolling: 3.0
  result: 3.0
  cooldown: 2.5
detection:
  hsv_min: [0, 120, 120]
  hsv_max: [40, 255, 255]
  blur_kernel: 11
  morph_kernel: 5
  morph_iterations: 1
  min_contour_area: 1500
  buffer_duration: 0.6
  min_wave_span: 0.2
  min_wave_velocity: 0.4
  cooldown: 1.5
  roi:
    x: 0.2
    y: 0.1
    width: 0.6
    height: 0.8
